---
core:
  num_workers: 100
  # raise_on_error: True

inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "inventory/hosts.yml"
    group_file: "inventory/groups.yml"
    defaults_file: "inventory/defaults.yml"