
core-routers:
    username: noc
    password: n0c098!
    platform: ios
    data:
         asn: 18190
        
cn-3d-office:
    username: asoltes
    password: bsit113092
    platform: ios
    data:
         asn: 18190
        